name: hacktues
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py39h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=openblas
  - bleach=3.3.0=pyhd3eb1b0_0
  - ca-certificates=2020.12.5=ha878542_0
  - certifi=2020.12.5=py39hf3d152e_1
  - cffi=1.14.5=py39h261ae71_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39h06a4308_0
  - icu=58.2=hf484d3e_1000
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - ipykernel=5.3.4=py39hb070fc8_0
  - ipython=7.21.0=py39hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39h06a4308_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=pyhd8ed1ab_2
  - jupyter_core=4.7.1=py39h06a4308_0
  - jupyter_highlight_selected_word=0.2.0=py39hf3d152e_1002
  - jupyter_latex_envs=1.4.6=pyhd8ed1ab_1002
  - jupyter_nbextensions_configurator=0.4.1=py39hf3d152e_2
  - jupyterlab_pygments=0.1.2=py_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libopenblas=0.3.10=h5a2b251_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libxml2=2.9.10=hb55368b_3
  - libxslt=1.1.34=hc22bd24_0
  - lxml=4.6.2=py39h9120a33_0
  - markupsafe=1.1.1=py39h27cfd23_0
  - mistune=0.8.4=py39h27cfd23_1000
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.0.7=py39h06a4308_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.2.0=py39h06a4308_0
  - numpy=1.19.2=py39h87658db_0
  - numpy-base=1.19.2=py39h0f7b65f_0
  - openssl=1.1.1j=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py39ha9443f7_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py39h06a4308_1
  - parso=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py39h06a4308_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py39h27cfd23_0
  - python=3.9.2=hdb3f193_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python_abi=3.9=1_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.3.1=py39h38d8fee_1
  - pyzmq=20.0.0=py39h2531618_1
  - readline=8.1=h27cfd23_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39h06a4308_0
  - six=1.15.0=py39h06a4308_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.2=py39h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py39h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2020f=h52ac0ba_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39h06a4308_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h516909a_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - bcrypt==3.2.0
    - cached-property==1.5.2
    - chardet==4.0.0
    - cryptography==3.4.6
    - distro==1.5.0
    - docker==4.4.4
    - docker-compose==1.28.5
    - dockerpty==0.4.1
    - docopt==0.6.2
    - idna==2.10
    - neo4j==4.2.1
    - osmium==3.1.3
    - paramiko==2.7.2
    - pynacl==1.4.0
    - python-dotenv==0.15.0
    - requests==2.25.1
    - texttable==1.6.3
    - urllib3==1.26.3
    - websocket-client==0.58.0
    - yapf==0.30.0
